Add `add deviceset` command
project-flotta/flotta-dev-cli pull request #60
Opened 2022-08-08 14:09 UTC by arielireni

Added deviceset implementation to the resources package.
Added `add deviceset -n <deviceset-name> -s <size-of-deviceset> -p <device-name-prefix>`, where only the name flag is mandatory.

Signed-off-by: arielireni <aireni@redhat.com>

2022-08-08 14:35 UTC, masayag requested changes

2022-08-08 14:35 UTC, masayag commented on internal/cmd/add/deviceset.go
> +			// if devices prefix has not been specified, define a random prefix
pls update the comment. we'll use the deviceset name instead.

2022-08-08 14:35 UTC, masayag commented on internal/cmd/add/deviceset.go
> +	deviceSetCmd.Flags().IntVarP(&deviceSetSize, "size", "s", 0, "size of the deviceset")
let's explain a bit more about this, e.g.: "the amount of edge devices to be created and added to the device set"

2022-08-08 14:35 UTC, masayag commented on internal/cmd/add/deviceset.go
> +			}
How about adding logs here for each successful device registration? 
"Device x1 was added successfully to device-set Y1 (1/5)"
"Device x2 was added successfully to device-set Y2 (2/5)"
...

2022-08-08 14:35 UTC, masayag commented on internal/cmd/add/deviceset.go
> +	dvc.Labels["flotta/member-of"] = deviceSetName
Is there an option to include this in device creation?

2022-08-08 14:54 UTC, gciavarrini commented on internal/cmd/add/deviceset.go
> +			}
Question: in case of multiple execution of `add deviceset`, will the command fail if the specified `deviceSetName` already exists?

2022-08-08 15:24 UTC, arielireni commented on internal/cmd/add/deviceset.go
> +			// if devices prefix has not been specified, define a random prefix
done

2022-08-08 15:24 UTC, arielireni commented on internal/cmd/add/deviceset.go
> +	deviceSetCmd.Flags().IntVarP(&deviceSetSize, "size", "s", 0, "size of the deviceset")
done

2022-08-08 15:39 UTC, arielireni commented on internal/cmd/add/deviceset.go
> +			}
Yes, with the error message:
```
→ ./bin/flotta add deviceset -n set1 -s 1
Create deviceset failed: edgedevicesets.management.project-flotta.io "set1" already exists
```

2022-08-08 15:41 UTC, arielireni commented on internal/cmd/add/deviceset.go
> +			}
done

2022-08-08 15:47 UTC, masayag commented on internal/cmd/add/deviceset.go
> +	dvc.Labels["flotta/member-of"] = deviceSetName
actually, the edgedevice CR is created by the device-server.

2022-08-08 16:06 UTC, masayag approved these changes

2022-08-09 06:31 UTC, gciavarrini approved these changes

2022-08-09 06:53 UTC, merged